import crypto from "node:crypto";

const REQUIRED_ENV_VARS = [
  "GOOGLE_WALLET_ISSUER_ID",
  "GOOGLE_WALLET_SERVICE_ACCOUNT_JSON",
];

function base64UrlEncode(input) {
  const buffer = Buffer.isBuffer(input) ? input : Buffer.from(String(input), "utf8");
  return buffer
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/g, "");
}

function sanitizeIdPart(value, fallback) {
  const raw = String(value || "").trim();
  const cleaned = raw.replace(/[^a-zA-Z0-9._-]/g, "_").slice(0, 60);
  return cleaned || fallback;
}

function parseServiceAccount(rawValue) {
  if (!rawValue || String(rawValue).trim() === "") {
    throw new Error("Missing GOOGLE_WALLET_SERVICE_ACCOUNT_JSON");
  }

  let parsed;
  try {
    parsed = JSON.parse(String(rawValue).trim());
  } catch {
    throw new Error("GOOGLE_WALLET_SERVICE_ACCOUNT_JSON is not valid JSON");
  }

  if (!parsed.client_email) {
    throw new Error("Service account JSON is missing client_email");
  }
  if (!parsed.private_key) {
    throw new Error("Service account JSON is missing private_key");
  }

  return parsed;
}

function signJwtRs256(header, payload, privateKeyPem) {
  const encodedHeader = base64UrlEncode(JSON.stringify(header));
  const encodedPayload = base64UrlEncode(JSON.stringify(payload));
  const signingInput = `${encodedHeader}.${encodedPayload}`;

  const signer = crypto.createSign("RSA-SHA256");
  signer.update(signingInput);
  signer.end();
  const signature = signer.sign(privateKeyPem);
  const encodedSignature = base64UrlEncode(signature);

  return `${signingInput}.${encodedSignature}`;
}

async function readJsonBody(req) {
  if (req.body && typeof req.body === "object") return req.body;

  const contentType = String(req.headers["content-type"] || "").toLowerCase();
  if (!contentType.includes("application/json")) return null;

  const chunks = [];
  for await (const chunk of req) chunks.push(chunk);
  const raw = Buffer.concat(chunks).toString("utf8").trim();
  if (!raw) return null;

  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET,POST,OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") return res.status(204).end();
  if (!["GET", "POST"].includes(req.method || "")) {
    return res.status(405).json({ ok: false, error: "Use GET or POST" });
  }

  try {
    const missing = REQUIRED_ENV_VARS.filter((name) => {
      const value = process.env[name];
      return !value || String(value).trim() === "";
    });

    if (missing.length) {
      return res.status(500).json({
        ok: false,
        error: `Missing required environment variables: ${missing.join(", ")}`,
      });
    }

    const issuerId = String(process.env.GOOGLE_WALLET_ISSUER_ID).trim();
    const serviceAccount = parseServiceAccount(process.env.GOOGLE_WALLET_SERVICE_ACCOUNT_JSON);

    const body = req.method === "POST" ? (await readJsonBody(req)) || {} : {};
    const classSuffix = sanitizeIdPart(body.classSuffix, "generic_pass_class");
    const objectSuffix = sanitizeIdPart(
      body.objectSuffix,
      `generic_pass_${Date.now()}_${crypto.randomBytes(4).toString("hex")}`
    );

    const classId = `${issuerId}.${classSuffix}`;
    const objectId = `${issuerId}.${objectSuffix}`;
    const nowSeconds = Math.floor(Date.now() / 1000);

    const genericClass = {
      id: classId,
      issuerName: String(body.issuerName || "Demo Issuer").slice(0, 40),
      reviewStatus: "UNDER_REVIEW",
    };

    const genericObject = {
      id: objectId,
      classId,
      state: "ACTIVE",
      cardTitle: {
        defaultValue: {
          language: "en-US",
          value: String(body.cardTitle || "Demo Pass").slice(0, 40),
        },
      },
      header: {
        defaultValue: {
          language: "en-US",
          value: String(body.header || "Save to Google Wallet").slice(0, 40),
        },
      },
      subheader: {
        defaultValue: {
          language: "en-US",
          value: String(body.subheader || "Generic Pass").slice(0, 40),
        },
      },
      textModulesData: [
        {
          id: "details",
          header: "Details",
          body: String(body.details || "Generated by /api/google-save").slice(0, 500),
        },
      ],
    };

    const payload = {
      iss: serviceAccount.client_email,
      aud: "google",
      typ: "savetowallet",
      iat: nowSeconds,
      payload: {
        genericClasses: [genericClass],
        genericObjects: [genericObject],
      },
    };

    const token = signJwtRs256({ alg: "RS256", typ: "JWT" }, payload, serviceAccount.private_key);
    const saveUrl = `https://pay.google.com/gp/v/save/${token}`;

    return res.status(200).json({ ok: true, saveUrl });
  } catch (error) {
    return res.status(500).json({
      ok: false,
      error: error instanceof Error ? error.message : String(error),
    });
  }
}
