import crypto from "node:crypto";
import { readJsonBodyStrict } from "../lib/requestValidation.js";

const REQUIRED_ENV_VARS = [
  "GOOGLE_WALLET_ISSUER_ID",
  "GOOGLE_WALLET_SERVICE_ACCOUNT_JSON",
];

class HttpError extends Error {
  constructor(status, message, missing = []) {
    super(message);
    this.status = status;
    this.missing = missing;
  }
}

function base64UrlEncode(input) {
  const buffer = Buffer.isBuffer(input) ? input : Buffer.from(String(input), "utf8");
  return buffer
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/g, "");
}

function sanitizeIdPart(value, fallback) {
  const raw = String(value || "").trim();
  const cleaned = raw.replace(/[^a-zA-Z0-9._-]/g, "_").slice(0, 60);
  return cleaned || fallback;
}

function parseServiceAccount(rawValue) {
  if (!rawValue || String(rawValue).trim() === "") {
    throw new HttpError(400, "Missing required environment variables", [
      "GOOGLE_WALLET_SERVICE_ACCOUNT_JSON",
    ]);
  }

  let parsed;
  try {
    parsed = JSON.parse(String(rawValue).trim());
  } catch {
    throw new HttpError(400, "GOOGLE_WALLET_SERVICE_ACCOUNT_JSON is not valid JSON");
  }

  if (!parsed.client_email) {
    throw new HttpError(400, "Service account JSON is missing client_email");
  }
  if (!parsed.private_key) {
    throw new HttpError(400, "Service account JSON is missing private_key");
  }

  return parsed;
}

function signJwtRs256(header, payload, privateKeyPem) {
  const encodedHeader = base64UrlEncode(JSON.stringify(header));
  const encodedPayload = base64UrlEncode(JSON.stringify(payload));
  const signingInput = `${encodedHeader}.${encodedPayload}`;

  const signer = crypto.createSign("RSA-SHA256");
  signer.update(signingInput);
  signer.end();
  const signature = signer.sign(privateKeyPem);
  const encodedSignature = base64UrlEncode(signature);

  return `${signingInput}.${encodedSignature}`;
}

function normalizeJoinUrl(raw) {
  const value = String(raw || "").trim();
  if (!value) return null;
  try {
    const parsed = new URL(value);
    if (!["http:", "https:"].includes(parsed.protocol)) return null;
    return parsed.toString();
  } catch {
    return null;
  }
}

function resolveJoinUrl(body) {
  const explicitJoinUrl = body?.joinUrl;
  if (explicitJoinUrl !== undefined) {
    const parsed = normalizeJoinUrl(explicitJoinUrl);
    if (!parsed) {
      throw new HttpError(400, "Invalid joinUrl. Expected an absolute http(s) URL.");
    }
    return parsed;
  }

  const fallbackCandidates = [body?.eventUrl, body?.url, body?.ctaUrl];
  for (const candidate of fallbackCandidates) {
    const parsed = normalizeJoinUrl(candidate);
    if (parsed) return parsed;
  }
  return null;
}

export function buildGenericClassAndObject({ issuerId, body, classSuffix, objectSuffix }) {
  const classId = `${issuerId}.${classSuffix}`;
  const objectId = `${issuerId}.${objectSuffix}`;
  const joinUrl = resolveJoinUrl(body);

  const genericClass = {
    id: classId,
    issuerName: String(body.issuerName || "Demo Issuer").slice(0, 40),
    reviewStatus: "UNDER_REVIEW",
  };

  const genericObject = {
    id: objectId,
    classId,
    state: "ACTIVE",
    cardTitle: {
      defaultValue: {
        language: "en-US",
        value: String(body.cardTitle || "Demo Pass").slice(0, 40),
      },
    },
    header: {
      defaultValue: {
        language: "en-US",
        value: String(body.header || "Save to Google Wallet").slice(0, 40),
      },
    },
    subheader: {
      defaultValue: {
        language: "en-US",
        value: String(body.subheader || "Generic Pass").slice(0, 40),
      },
    },
    textModulesData: [
      {
        id: "details",
        header: "Details",
        body: String(body.details || "Generated by /api/google-save").slice(0, 500),
      },
    ],
  };

  if (joinUrl) {
    genericObject.linksModuleData = {
      uris: [
        {
          id: "join",
          description: "Join",
          uri: joinUrl,
        },
      ],
    };
    genericObject.appLinkData = {
      webAppLinkInfo: {
        appTarget: {
          targetUri: {
            uri: joinUrl,
            description: "Join",
          },
        },
      },
    };
  }

  return { classId, objectId, genericClass, genericObject };
}

export default async function handler(req, res) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET,POST,OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") return res.status(204).end();
  if (!["GET", "POST"].includes(req.method || "")) {
    return res.status(405).json({ ok: false, error: "Use GET or POST" });
  }

  try {
    const missing = REQUIRED_ENV_VARS.filter((name) => {
      const value = process.env[name];
      return !value || String(value).trim() === "";
    });

    if (missing.length) {
      return res.status(400).json({
        ok: false,
        error: "Missing required environment variables",
        missing,
      });
    }

    const issuerId = String(process.env.GOOGLE_WALLET_ISSUER_ID).trim();
    const serviceAccount = parseServiceAccount(process.env.GOOGLE_WALLET_SERVICE_ACCOUNT_JSON);

    let body = {};
    if (req.method === "POST") {
      const parsedBody = await readJsonBodyStrict(req, { allowEmpty: true });
      if (!parsedBody.ok) {
        throw new HttpError(parsedBody.status, parsedBody.error);
      }
      body = parsedBody.body || {};
    }
    const classSuffix = sanitizeIdPart(body.classSuffix, "generic_pass_class");
    const objectSuffix = sanitizeIdPart(
      body.objectSuffix,
      `generic_pass_${Date.now()}_${crypto.randomBytes(4).toString("hex")}`
    );

    const { genericClass, genericObject } = buildGenericClassAndObject({
      issuerId,
      body,
      classSuffix,
      objectSuffix,
    });
    const nowSeconds = Math.floor(Date.now() / 1000);

    const payload = {
      iss: serviceAccount.client_email,
      aud: "google",
      typ: "savetowallet",
      iat: nowSeconds,
      payload: {
        genericClasses: [genericClass],
        genericObjects: [genericObject],
      },
    };

    const token = signJwtRs256({ alg: "RS256", typ: "JWT" }, payload, serviceAccount.private_key);
    const saveUrl = `https://pay.google.com/gp/v/save/${token}`;

    return res.status(200).json({ ok: true, saveUrl });
  } catch (error) {
    if (error instanceof HttpError) {
      return res.status(error.status).json({
        ok: false,
        error: error.message,
        missing: error.missing,
      });
    }
    return res.status(500).json({
      ok: false,
      error: error instanceof Error ? error.message : String(error),
      missing: [],
    });
  }
}
